# GitHub Action for generating a contribution graph
# with a snake eating your contributions.

name: Generate Snake

on:
  # Run every 6 hours
  schedule:
    - cron: "0 */6 * * *"

  # Allow manual execution from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Generate the contribution snake
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Subhradip304

          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Deploy generated files to the output branch
      - name: Deploy Snake
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update contribution snake [skip ci]"
